name: eduplay
description: "EduPlay - A colorful educational game app for Sri Lankan school children"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Backend
  supabase_flutter: ^2.6.0

  # State management
  provider: ^6.1.2

  # Fonts & animations
  google_fonts: ^6.2.1
  confetti: ^0.7.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/one.png
    - assets/two.png
    - assets/three.png
    - assets/cloud1.png
    - assets/cloud2.png
    - assets/four.png
